#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_WINDOWS = $(INC) -Ilib\Windows\include
CFLAGS_WINDOWS = $(CFLAGS) -fexpensive-optimizations -O3 -Wnon-virtual-dtor -Wredundant-decls -Wfloat-equal -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -pedantic -Wextra -Wall -std=c++11 -DSFML_STATIC
RESINC_WINDOWS = $(RESINC)
RCFLAGS_WINDOWS = $(RCFLAGS)
LIBDIR_WINDOWS = $(LIBDIR) -Llib\Windows\lib
LIB_WINDOWS = $(LIB)-lsfml-system-s -lwinmm
LDFLAGS_WINDOWS =  -s
OBJDIR_WINDOWS = obj\\Windows
DEP_WINDOWS = 
OUT_WINDOWS = bin\\Windows\\LPT_Motor_Driver.exe

OBJ_WINDOWS = $(OBJDIR_WINDOWS)\\src\\driver\\access.o $(OBJDIR_WINDOWS)\\src\\driver\\driver.o $(OBJDIR_WINDOWS)\\src\\main.o $(OBJDIR_WINDOWS)\\src\\ui\\gui\\gui.o $(OBJDIR_WINDOWS)\\src\\ui\\tui\\tui.o $(OBJDIR_WINDOWS)\\src\\ui\\ui.o

all: windows

clean: clean_windows

before_windows: 
	cmd /c if not exist bin\\Windows md bin\\Windows
	cmd /c if not exist $(OBJDIR_WINDOWS)\\src\\driver md $(OBJDIR_WINDOWS)\\src\\driver
	cmd /c if not exist $(OBJDIR_WINDOWS)\\src md $(OBJDIR_WINDOWS)\\src
	cmd /c if not exist $(OBJDIR_WINDOWS)\\src\\ui\\gui md $(OBJDIR_WINDOWS)\\src\\ui\\gui
	cmd /c if not exist $(OBJDIR_WINDOWS)\\src\\ui\\tui md $(OBJDIR_WINDOWS)\\src\\ui\\tui
	cmd /c if not exist $(OBJDIR_WINDOWS)\\src\\ui md $(OBJDIR_WINDOWS)\\src\\ui

after_windows: 
	"scripts/release_windows.bat"

windows: before_windows out_windows after_windows

out_windows: before_windows $(OBJ_WINDOWS) $(DEP_WINDOWS)
	$(LD) $(LIBDIR_WINDOWS) -o $(OUT_WINDOWS) $(OBJ_WINDOWS)  $(LDFLAGS_WINDOWS) $(LIB_WINDOWS)

$(OBJDIR_WINDOWS)\\src\\driver\\access.o: src\\driver\\access.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\driver\\access.cpp -o $(OBJDIR_WINDOWS)\\src\\driver\\access.o

$(OBJDIR_WINDOWS)\\src\\driver\\driver.o: src\\driver\\driver.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\driver\\driver.cpp -o $(OBJDIR_WINDOWS)\\src\\driver\\driver.o

$(OBJDIR_WINDOWS)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\main.cpp -o $(OBJDIR_WINDOWS)\\src\\main.o

$(OBJDIR_WINDOWS)\\src\\ui\\gui\\gui.o: src\\ui\\gui\\gui.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\ui\\gui\\gui.cpp -o $(OBJDIR_WINDOWS)\\src\\ui\\gui\\gui.o

$(OBJDIR_WINDOWS)\\src\\ui\\tui\\tui.o: src\\ui\\tui\\tui.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\ui\\tui\\tui.cpp -o $(OBJDIR_WINDOWS)\\src\\ui\\tui\\tui.o

$(OBJDIR_WINDOWS)\\src\\ui\\ui.o: src\\ui\\ui.cpp
	$(CXX) $(CFLAGS_WINDOWS) $(INC_WINDOWS) -c src\\ui\\ui.cpp -o $(OBJDIR_WINDOWS)\\src\\ui\\ui.o

clean_windows: 
	cmd /c del /f $(OBJ_WINDOWS) $(OUT_WINDOWS)
	cmd /c rd bin\\Windows
	cmd /c rd $(OBJDIR_WINDOWS)\\src\\driver
	cmd /c rd $(OBJDIR_WINDOWS)\\src
	cmd /c rd $(OBJDIR_WINDOWS)\\src\\ui\\gui
	cmd /c rd $(OBJDIR_WINDOWS)\\src\\ui\\tui
	cmd /c rd $(OBJDIR_WINDOWS)\\src\\ui

.PHONY: before_windows after_windows clean_windows

